---
apiVersion: v1
kind: Service
metadata:
  name: conductors
  labels:
    app: conductors
spec:
  type: NodePort
  selector:
    app: conductors
  ports:
  - protocol: TCP
    port: 8050
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: conductors
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: conductors
    spec:
      containers:
      - name: conductors
        image: 'docker.io/shabushabu/javashop.conductors:latest'
        ports:
        - containerPort: 8050
        env:
          - name: SPLUNK_OTEL_AGENT
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: service.name=conductors,deployment.environment=dd-k8s-1-25-2
          
          - name: SPLUNK_METRICS_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9943
          
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):4317
          
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://$(SPLUNK_OTEL_AGENT):9080/v1/trace

                # livenessProbe:
                #httpGet:
                #path: /healthcheck
                #port: 8025
                #initialDelaySeconds: 30
                #timeoutSeconds: 1
